[olricd]
partitionCount = 19
backupCount = 0
backupMode = 0
name = "0.0.0.0:3320"
tcpAddr = "0.0.0.0:3422"
#certFile = "/home/burak/Projects/server.pem"
#keyFile = "/home/burak/Projects/server.key"
serializer = "msgpack"
keepAlivePeriod = "300s"
# 1MB by default
maxValueSize = 1048576 

[snapshot]
enabled = true
dir = "/home/burak/olricd-data"
interval = "1s"
gcInterval  = "5m"
gcDiscardRatio = 0.7

[logging]
level = "DEBUG"
output = "stderr"

[httpClient]
dialerTimeout       = "5s"
insecureSkipVerify  = true
timeout             = "60s"

[memberlist]
environment = "local"
addr = "0.0.0.0:3322"
enableCompression = false
peers = [
  "localhost:3325"
]
